import { useCallback, useEffect, useState } from 'react';
import { subscriptionApi } from '../../services/subscriptionApi';

const Stat = ({ label, value }) => <div className="rounded-lg border border-slate-200 bg-white p-4 shadow-sm"><div className="text-sm text-slate-500">{label}</div><div className="mt-1 text-2xl font-semibold text-slate-950">{value}</div></div>;

export const SubscriptionAnalytics = () => {
  const [analytics, setAnalytics] = useState(null);
  const [error, setError] = useState('');
  const load = useCallback(async () => { try { const response = await subscriptionApi.getAdminAnalytics(); setAnalytics(response.data.data.analytics); setError(''); } catch (apiError) { setError(apiError.response?.data?.message || 'Unable to load subscription analytics.'); } }, []);
  useEffect(() => { load(); window.addEventListener('healthiffy:subscription-updated', load); return () => window.removeEventListener('healthiffy:subscription-updated', load); }, [load]);
  return <main className="min-h-screen bg-slate-50 px-4 py-8"><section className="mx-auto max-w-7xl"><div className="mb-6"><p className="text-sm font-medium uppercase tracking-wide text-emerald-700">Admin</p><h1 className="text-3xl font-semibold text-slate-950">Subscription Analytics</h1></div>{error && <p className="mb-4 rounded-md bg-red-50 px-3 py-2 text-sm text-red-700">{error}</p>}{!analytics ? <p className="rounded-lg border border-slate-200 bg-white p-5 text-sm text-slate-600">Loading analytics...</p> : <><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><Stat label="Active Subscribers" value={analytics.activeSubscribers} /><Stat label="Today's Expected Meals" value={analytics.expectedMeals} /><Stat label="Today's Delivered" value={analytics.deliveredMeals} /><Stat label="Today's Pending" value={analytics.pendingMeals} /><Stat label="Monthly Revenue" value={`₹${analytics.monthlyRevenue.toLocaleString('en-IN')}`} /></div><div className="mt-6 grid gap-6 lg:grid-cols-2"><section className="rounded-lg border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-4 text-lg font-semibold">Meals by Branch Today</h2><div className="space-y-3">{analytics.mealsByBranch.map((item) => <div key={item.branchId} className="flex items-center justify-between border-b border-slate-100 pb-3"><span className="font-medium">{item.branchName}</span><span className="text-sm text-slate-600">{item.delivered} delivered · {item.pending} pending</span></div>)}</div></section><section className="rounded-lg border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-4 text-lg font-semibold">Monthly Revenue by Branch</h2><div className="space-y-3">{analytics.revenueByBranch.map((item) => <div key={item.branchId} className="flex items-center justify-between border-b border-slate-100 pb-3"><span className="font-medium">{item.branchName}</span><span className="text-sm font-semibold">₹{item.revenue.toLocaleString('en-IN')}</span></div>)}</div></section><section className="rounded-lg border border-slate-200 bg-white p-5 shadow-sm lg:col-span-2"><h2 className="mb-4 text-lg font-semibold">Worker Delivery Count Today</h2><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{analytics.workerDeliveryCount.map((item) => <div key={item.workerId} className="rounded-md border border-slate-200 p-3"><div className="font-medium">{item.workerName}</div><div className="mt-1 text-sm text-slate-600">{item.deliveries} deliveries</div></div>)}</div></section></div></>}</section></main>;
};

